export const GovernanceBSCABI = [
    {
        inputs: [{ internalType: "address", name: "_pgvToken", type: "address" }],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    { inputs: [], name: "AlreadyVoted", type: "error" },
    { inputs: [], name: "InsufficientProposerBalance", type: "error" },
    { inputs: [], name: "NoVotingPower", type: "error" },
    { inputs: [], name: "ProposalAlreadyExecuted", type: "error" },
    { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
    { inputs: [], name: "VotingPeriodEnded", type: "error" },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
            { indexed: false, internalType: "string", name: "title", type: "string" },
            { indexed: false, internalType: "string", name: "description", type: "string" },
            { indexed: false, internalType: "uint256", name: "startTime", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "endTime", type: "uint256" },
            { indexed: false, internalType: "uint256", name: "snapshotBlock", type: "uint256" },
        ],
        name: "ProposalCreated",
        type: "event",
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: "uint256", name: "id", type: "uint256" },
            {
                indexed: false,
                internalType: "enum GovernanceBSC.ProposalStatus",
                name: "status",
                type: "uint8",
            },
        ],
        name: "ProposalExecuted",
        type: "event",
    },
    {
        inputs: [
            { internalType: "string", name: "_title", type: "string" },
            { internalType: "string", name: "_description", type: "string" },
            { internalType: "uint256", name: "_durationDays", type: "uint256" },
        ],
        name: "createProposal",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "_id", type: "uint256" }],
        name: "executeProposal",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "uint256", name: "_proposalId", type: "uint256" },
            { internalType: "address", name: "_voter", type: "address" },
        ],
        name: "getVotingPower",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "uint256", name: "", type: "uint256" },
            { internalType: "address", name: "", type: "address" },
        ],
        name: "hasVoted",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "pgvToken",
        outputs: [{ internalType: "contract ERC20Votes", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "proposalCount",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        name: "proposals",
        outputs: [
            { internalType: "uint256", name: "id", type: "uint256" },
            { internalType: "string", name: "title", type: "string" },
            { internalType: "string", name: "description", type: "string" },
            { internalType: "uint256", name: "yesVotes", type: "uint256" },
            { internalType: "uint256", name: "noVotes", type: "uint256" },
            { internalType: "uint256", name: "startTime", type: "uint256" },
            { internalType: "uint256", name: "endTime", type: "uint256" },
            { internalType: "enum GovernanceBSC.ProposalStatus", name: "status", type: "uint8" },
            { internalType: "uint256", name: "snapshotBlock", type: "uint256" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "uint256", name: "_id", type: "uint256" },
            { internalType: "bool", name: "_support", type: "bool" },
        ],
        name: "vote",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
] as const;
